

modLoader="javafml" #mandatory

loaderVersion="[33,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="The MIT License (MIT)" #mandatory

issueTrackerURL="https://github.com/bisson2000/LavaFurnace/issues" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

modId="lavafurnace" #mandatory

version="1.16.2-1.0.3" #mandatory

displayName="Lava Furnace" #mandatory

#updateJSONURL="https://github.com/bisson2000/LavaFurnace" #optional

displayURL="https://github.com/bisson2000/LavaFurnace" #optional

logoFile="lavaFurnaceIcon.png" #optional

credits="The minecraft modding community" #optional

authors="bisson2000" #optional

description='''

This mod adds a Lava Furnace that smelts items faster with hot fluids

'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.lavafurnace]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[33.0.0,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.lavafurnace]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,)"
    ordering="NONE"
    side="BOTH"
