name: Feature request
description: Suggest an idea for this project
labels: 
  - enhancement
assignees:
  - bisson2000
body:
  - type: markdown
    attributes: 
      value: |
        Please search to see if an issue already exists for the feature request.

        ---
  - type: textarea
    id: relatedToProblem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: ex. I'm always frustrated when '....'
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: additionalContext
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
